spring.application.name=athena-server

server.port=8080

ollama.url=http://localhost:11434

ollama.text-model=qwen2.5-coder:7b
ollama.vision-model=gemma3:4b
ollama.vision-models=gemma3:4b,gemma3:12b,gemma3:27b

athena.storage.attachments=./athena-data/attachments

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.datasource.url=jdbc:postgresql://localhost:5432/athena
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
